In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [7]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[7,8,9],[4,5,6]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [14]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [4]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [5]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [8]:
np.random().rand(5)

TypeError: 'module' object is not callable

In [10]:
arr = np.arange(25)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
ranarr = np.random.randint(0,50,10)

In [13]:
ranarr

array([44, 37, 38,  2,  1, 13,  3, 29, 27, 27])

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
ranarr .max()

44

In [17]:
ranarr.min()

1

In [18]:
ranarr.argmax()

0

In [19]:
ranarr.argmin()

4

In [22]:
ranarr.shape

(10,)

In [23]:
ranarr.dtype

dtype('int32')

# Numpy indexing and selection

In [24]:
arr = np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr[8]

8

In [27]:
arr[1:5]

array([1, 2, 3, 4])

In [28]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [29]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr[0:5] = 100

In [31]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [32]:
arr = np.arange(0,11)

In [33]:
sarr = arr[0:5]

In [34]:
sarr

array([0, 1, 2, 3, 4])

In [35]:
sarr[:] = 99

In [36]:
sarr

array([99, 99, 99, 99, 99])

In [37]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [38]:
arr_copy = arr.copy()

In [39]:
arr_copy[:] = 100

In [40]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [41]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [43]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

## 

In [44]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
arr_2d[0][0]

5

In [46]:
arr_2d[0]

array([ 5, 10, 15])

In [48]:
arr_2d[2,1]

40

In [49]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [50]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [51]:
arr = np.arange(10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
bool_arr = arr > 5

In [56]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [57]:
arr[bool_arr]

array([6, 7, 8, 9])

In [58]:
arr[arr > 5]

array([6, 7, 8, 9])

In [59]:
arr[arr < 3]

array([0, 1, 2])

# Numpy Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr* arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
arr * 8

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [8]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [10]:
 1/ arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [11]:
 arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [13]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [14]:
np.max(arr)

10

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [16]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])